### ISSUE TITLE
How can i fix it?

### ISSUE THREAD

**Issue by ZONEXIEO** [FlafyDev/among-us-discord#2]
File "C:\Users\Oren\Downloads\Compressed\among-us-discord-version-2\bot\bot_discord.py", line 28, in <module>
    def add_room_to_refresh(room_: Room):
NameError: name 'Room' is not defined

**Comment by FlafyDev** [comment]
Already answered this in the Discord but for people who might stumble upon this in the future, you need to run the `main.py` file.
